name: cysignals on cygwin

on:
  pull_request:
    types: [opened, synchronize]
  push:
    tags:
      - '*'

env:
  MAKE: make -j8
  SAGE_NUM_THREADS: 3
  CYGWIN: winsymlinks:native

jobs:
    build:
        runs-on: windows-latest

        strategy:
          fail-fast: false
          matrix:
            python-version: [36]
        steps:
        - run: |
            git config --global core.autocrlf false
            git config --global core.symlinks true
        - uses: actions/checkout@v1
        - name: install cygwin and minimal prerequisites with choco
          shell: bash {0}
          run: |
            choco --version
            choco install make autoconf gcc-core gcc-g++ python${{ matrix.python-version }}-devel --source cygwin
        - name: configure
          run: |
            C:\\tools\\cygwin\\bin\\bash -l -x -c 'export PATH=/usr/local/bin:/usr/bin && cd $(cygpath -u "$GITHUB_WORKSPACE") && make configure && ./configure'
        - name: install
          run: |
            C:\\tools\\cygwin\\bin\\bash -l -x -c 'export PATH=/usr/local/bin:/usr/bin && cd $(cygpath -u "$GITHUB_WORKSPACE") && python3.6 setup.py build_ext -i'
        - name: test
          run: |
            C:\\tools\\cygwin\\bin\\bash -l -x -c 'export PATH=/usr/local/bin:/usr/bin && cd $(cygpath -u "$GITHUB_WORKSPACE") && make check-all PYTHON=python3.6'

