name: cysignals

on:
    pull_request:
        types: [opened, synchronize]
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [2.7, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9]
        steps:
        - name: Set up the repository
          uses: actions/checkout@v2
          with:
              submodules: recursive
              fetch-depth: 0
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install setuptools Cython Sphinx flake8
        - name: Run check-all (Linux & Mac)
          if: runner.os != 'Windows'
          run: |
              make check-all
        - name: Build (Windows)
          if: runner.os == 'Windows'
          run: |
              python setup.py install
        - name: Run checks (Windows)
          if: runner.os == 'Windows'
          run: |
              python -B rundoctests.py src/cysignals/*.pyx
              cd example && python setup.py clean build
